stages:
- build

variables:
  DEPENDENCIES_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/image:latest
  STORAGE_DRIVER: vfs # for buildah
  REGISTRY_AUTH_FILE: /root/auth.json

build_image:
  stage: build
  image: tomkukral/buildah
  before_script:
    - podman login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - buildah pull jupyter/tensorflow-notebook
    - buildah bud --format docker -t ${DEPENDENCIES_IMAGE_NAME} .
    - buildah push --authfile ${REGISTRY_AUTH_FILE} ${DEPENDENCIES_IMAGE_NAME}
  after_script:
    - podman logout "${CI_REGISTRY}"
  only:
    changes:
      - Dockerfile
      - binder/*
