stages:
  - build
  - test

variables:
  IMAGE: ${CI_REGISTRY_IMAGE}

build-image:
  stage: build 
  #and stage
  #services:
  #  - docker:dind
  #image: docker:git

  before_script:
    - docker login -u gitlab-ci-token -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull jupyter/tensorflow-notebook
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
  after_script:
    - 'docker logout $CI_REGISTRY'

  only:
    changes:
      - Dockerfile
      - environment.yml

image: ${IMAGE}

tests_python_packages:
  stage: test
  script:
    - pytest

tests_R_packages:
  stage: test
  script:
    - R < test_R_packages.r --no-save

tests_cpp_packages:
  stage: test
  script:
    - cling -std=c++14 < test_cpp_packages.cpp 2>&1 | tee log 2>&1 && test -z "`grep error log`"
    - cling -std=c++17 < test_cpp_packages.cpp 2>&1 | tee log 2>&1 && test -z "`grep error log`"
