stages:
  - build
  - test

variables:
  IMAGE: "${CI_REGISTRY_IMAGE}/image:latest"
  STORAGE_DRIVER: vfs # for buildah
  REGISTRY_AUTH_FILE: /root/auth.json

  IMAGE: ${CI_REGISTRY_IMAGE}

build-image:
  stage: build #and stage
  image: tomkukral/buildah:0.30

  before_script:
    - podman login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - buildah build-using-dockerfile --squash --format docker -t ${IMAGE} --file Dockerfile ./
    - buildah push --authfile ${REGISTRY_AUTH_FILE} ${IMAGE}
  after_script:
    - podman logout "${CI_REGISTRY}"
  only:
    changes:
      - Dockerfile
      - environment.yml

image: ${IMAGE}

tests_python_packages:
  stage: test
  script:
    - pytest

tests_R_packages:
  stage: test
  script:
    - R < test_R_packages.r --no-save

tests_cpp_packages:
  stage: test
  script:
    - cling -std=c++14 < test_cpp_packages.cpp 2>&1 | tee log 2>&1 && test -z "`grep error log`"
    - cling -std=c++17 < test_cpp_packages.cpp 2>&1 | tee log 2>&1 && test -z "`grep error log`"
